-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.appointment
(
    id serial NOT NULL,
    patient_id integer NOT NULL,
    doctor_id integer NOT NULL,
    appointment_date date NOT NULL,
    reason text COLLATE pg_catalog."default",
    appointment_status_id smallint NOT NULL,
    "time" character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT "Appointment_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.appointment_status
(
    id smallserial NOT NULL,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Appointment_Status_pkey" PRIMARY KEY (id),
    CONSTRAINT "Appointment_Status_name_key" UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.diagnosis
(
    id serial NOT NULL,
    code character varying(10) COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    diagnosis_type_id integer NOT NULL,
    CONSTRAINT "Diagnosis_pkey" PRIMARY KEY (id),
    CONSTRAINT "Diagnosis_code_key" UNIQUE (code),
    CONSTRAINT "Diagnosis_name_key" UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.diagnosis_type
(
    id smallserial NOT NULL,
    name character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Diagnosis_type_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.doctor
(
    id serial NOT NULL,
    first_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    specialization character varying(100) COLLATE pg_catalog."default" NOT NULL,
    code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Doctor_pkey" PRIMARY KEY (id),
    CONSTRAINT "Doctor_code_key" UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS public.medical_record
(
    id serial NOT NULL,
    patient_id integer NOT NULL,
    doctor_id integer NOT NULL,
    notes text COLLATE pg_catalog."default",
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    CONSTRAINT "MedicalRecord_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.medication
(
    id serial NOT NULL,
    code character varying(10) COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Medication_pkey" PRIMARY KEY (id),
    CONSTRAINT "Medication_code_key" UNIQUE (code),
    CONSTRAINT "Medication_name_key" UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.patient
(
    id serial NOT NULL,
    first_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    birth_date date NOT NULL,
    personal_id_number character varying(10) COLLATE pg_catalog."default" NOT NULL,
    gender character varying(64) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default",
    phone_number character varying(20) COLLATE pg_catalog."default",
    birth_city character varying(100) COLLATE pg_catalog."default" NOT NULL,
    permanent_city character varying(100) COLLATE pg_catalog."default" NOT NULL,
    street text COLLATE pg_catalog."default" NOT NULL,
    postal_code character varying(5) COLLATE pg_catalog."default" NOT NULL,
    insurance_number character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at time with time zone NOT NULL DEFAULT now(),
    blood_pressure character varying(10) COLLATE pg_catalog."default",
    weight real,
    height real,
    bmi real,
    doctor_id integer NOT NULL,
    CONSTRAINT "Patient_pkey" PRIMARY KEY (id),
    CONSTRAINT "Patient_email_key" UNIQUE (email),
    CONSTRAINT "Patient_personal_id_number_key" UNIQUE (personal_id_number),
    CONSTRAINT "Patient_phone_number_key" UNIQUE (phone_number)
);

CREATE TABLE IF NOT EXISTS public.points
(
    id serial NOT NULL,
    label text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    price real NOT NULL DEFAULT 0.00,
    points integer NOT NULL DEFAULT 0,
    CONSTRAINT points_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.prescription
(
    id serial NOT NULL,
    medical_record_id integer NOT NULL,
    medication_id integer NOT NULL,
    dosage character varying(100) COLLATE pg_catalog."default" NOT NULL,
    frequency character varying(100) COLLATE pg_catalog."default" NOT NULL,
    duration character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Prescription_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.record_diagnosis
(
    id serial NOT NULL,
    medical_record_id integer NOT NULL,
    diagnosis_id integer NOT NULL,
    CONSTRAINT "RecordDiagnosis_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.record_points
(
    id serial NOT NULL,
    medical_record_id integer NOT NULL,
    point_id integer NOT NULL,
    CONSTRAINT record_points_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.role
(
    id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Role_pkey" PRIMARY KEY (id),
    CONSTRAINT "Role_name_key" UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.token
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    token character varying(50) COLLATE pg_catalog."default" NOT NULL,
    validity timestamp with time zone NOT NULL DEFAULT (now() + '1 mon'::interval),
    CONSTRAINT "Token_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(50) COLLATE pg_catalog."default" NOT NULL,
    role_id integer NOT NULL,
    doctor_id integer NOT NULL,
    name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT "User_pkey" PRIMARY KEY (id),
    CONSTRAINT "User_email_key" UNIQUE (email)
);

ALTER TABLE IF EXISTS public.appointment
    ADD CONSTRAINT "Appointment_appointment_status_id_fkey" FOREIGN KEY (appointment_status_id)
    REFERENCES public.appointment_status (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.appointment
    ADD CONSTRAINT "Appointment_doctor_id_fkey" FOREIGN KEY (doctor_id)
    REFERENCES public.doctor (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.appointment
    ADD CONSTRAINT "Appointment_patient_id_fkey" FOREIGN KEY (patient_id)
    REFERENCES public.patient (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.diagnosis
    ADD CONSTRAINT "Diagnosis_diagnosis_type_id_fkey" FOREIGN KEY (diagnosis_type_id)
    REFERENCES public.diagnosis_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.medical_record
    ADD CONSTRAINT "MedicalRecord_doctor_id_fkey" FOREIGN KEY (doctor_id)
    REFERENCES public.doctor (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.medical_record
    ADD CONSTRAINT "MedicalRecord_patient_id_fkey" FOREIGN KEY (patient_id)
    REFERENCES public.patient (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.patient
    ADD CONSTRAINT fk_doctor FOREIGN KEY (doctor_id)
    REFERENCES public.doctor (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.prescription
    ADD CONSTRAINT "Prescription_medical_record_id_fkey" FOREIGN KEY (medical_record_id)
    REFERENCES public.medical_record (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.prescription
    ADD CONSTRAINT "Prescription_medication_id_fkey" FOREIGN KEY (medication_id)
    REFERENCES public.medication (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.record_diagnosis
    ADD CONSTRAINT "RecordDiagnosis_diagnosis_id_fkey" FOREIGN KEY (diagnosis_id)
    REFERENCES public.diagnosis (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.record_diagnosis
    ADD CONSTRAINT "RecordDiagnosis_medical_record_id_fkey" FOREIGN KEY (medical_record_id)
    REFERENCES public.medical_record (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.record_points
    ADD CONSTRAINT record_points_medical_record_id_fkey FOREIGN KEY (medical_record_id)
    REFERENCES public.medical_record (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.record_points
    ADD CONSTRAINT record_points_point_id_fkey FOREIGN KEY (point_id)
    REFERENCES public.points (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.token
    ADD CONSTRAINT "Token_user_id_fkey" FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT "User_role_id_fkey" FOREIGN KEY (role_id)
    REFERENCES public.role (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;